# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg', '0003_quote_quote_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='fav_users',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='hired',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='log_and_reg.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='wish_users',
            field=models.ManyToManyField(related_name='wish_items', to='log_and_reg.User'),
        ),
    ]
